### ISSUE TITLE
Cannot start the http-service

### ISSUE THREAD

**Issue by SchuldtOH** [henry-spanka/freeathome-api#1]
Hi,

thanks for creating this project. I used myself the Stadlberger-API and am trying to switch to this one, since I also updated my F@H access point.

After installing and starting the code, I get the following error in my log file:

2019-9-29 17:21:11 - INFO: Starting free@home API
2019-9-29 17:21:12 - ERR: TypeError: promise.finally is not a function
2019-9-29 17:21:13 - INFO: Starting free@home API
2019-9-29 17:21:13 - ERR: TypeError: promise.finally is not a function
2019-9-29 17:21:14 - INFO: Starting free@home API
2019-9-29 17:21:15 - ERR: TypeError: promise.finally is not a function
2019-9-29 17:21:16 - INFO: Starting free@home API

Did I miss to install anything? 
I only use the http-service, not the websocket.

Regards,
Kurt

**Comment by henry-spanka** [comment]
Hi Kurt,
which node version do you use?

I think the finally function was introduced in NodeJS 10. If you use an older version you need to update first.

**Comment by henry-spanka** [comment]
I have now explicitly set the required node version in the package file. Once a new version is released it should complain when trying to install the package on an unsupported system.

9adb6e814819fdd77dffe40d34e511ad0d172ff9

**Comment by SchuldtOH** [comment]
I use version v8. Unfortunatly for my Synology Disk Station it seems that no higher version is currently available. But I will search for it. Thanks for the hint.

**Comment by henry-spanka** [comment]
Hi,
I have now added documentation on how to use Docker. You should be able to use Docker with your Synology Disk Station.

See: https://www.synology.com/en-us/knowledgebase/DSM/help/Docker/docker_container

**Comment by felix-reck** [comment]
Hi,
I had the same error: „promise.finally...“ with node 9.9.0
After updating it, it’s working (now on version 11.6.0) 😊
I noticed one thing, if Homebridge is already running, I‘m not able to start the freeathome-api.
So the right order is to start the API first and then Homebridge.

Thank you for your awesome work 😊

**Comment by henry-spanka** [comment]
Hi,
thanks for the info. Why can't you start the API? Do you get an error message?

**Comment by felix-reck** [comment]
Hi,
I got an error message this morning. But I can‘t remember it (I think it was something like: can’t start api while ... is requesting...)
I just tried to reproduce it. But now I can start the API with Homebridge already running.
I let you know, if I get the error again.

Other than that, everything works great. The API is now running for 14 hours.

**Comment by timboozle** [comment]
Hi! Also trying to run this on a Synology NAS. 

I'm not too experienced with Docker but the config seems pretty straight forward.

However, the container crashes right away: `Error: Cannot find module '/usr/src/app/dist/index.js'`

**Comment by henry-spanka** [comment]
Hi Tim,
I can confirm this and I created a new issue for it #2. I'll try to take a look at it tomorrow.
