### ISSUE TITLE
Error should be exposed through events not just thrown. 

### ISSUE THREAD

**Issue by ZzAve** [henry-spanka/freeathome-api#10]
Whenever System-Access-Point throws an exception this is caught in application and handled there. However, it is handled because of a generic 'unhandledexception' block. This behaviour is discouraged by nodejs and will be deprecated soon. 

I propose to extend the broadcast functionality of System-Access-Point. Let it expose both updates and errors, introduce typing and make integration with freeathome-api as a lib even simpler.

**Comment by henry-spanka** [comment]
Hi,
you are right. You can open a PR for it if you like. Unfortunately I don't have much time at the moment to do this.

**Comment by ZzAve** [comment]
I haven't had the time to do this last week. This week I'll try and put in a PR!

**Comment by henry-spanka** [comment]
I think we can close this now? What do you think?

**Comment by ZzAve** [comment]
Jup! Fine with me
