### ISSUE TITLE
2.4.0: 2.3.1 version check prevents start

### ISSUE THREAD

**Issue by jafrka** [henry-spanka/freeathome-api#13]
Hi,
BJ does not seem to have changed something regarding the communication in firmware 2.4.0. E.g. switching lights and shutters does work.

The service does not start as the version comparison to 2.3.1 is not true. I changed it in the SystemAccessPoint.js manually to get work again. Could you change it in the source code?

Thank you.

**Comment by henry-spanka** [comment]
Thanks you for reporting this. I can verify this.

Fixed in 8c5ac90fce7cb1c194f6b828c461e4b8f5617cd4.
