### ISSUE TITLE
Question: API fully working, also on 2.4.0?

### ISSUE THREAD

**Issue by martin072** [henry-spanka/freeathome-api#14]
Hi,

I am still on 2.2.4 and noticed 2.4.0 is available with some nice new features that I would like to use. However, I am still using sstadlberger's API and still works fine (I use my own home automation). Can you confirm your version fully compatible and working with 2.4.0?

Thanks!

**Comment by henry-spanka** [comment]
Hi Martin,
yes 2.4.0 comes with a nice feature that implements tapping a sensor twice to activate a scene.
I have updated to 2.4.0 today and can confirm that no changes have been made to the protocol (at least no visible). The API works just as before.

Do you use the `set` or `input` API endpoints of sstadlberger's API? I have decided to not implement these endpoints as they are actuator specific and hard to maintain for all the different actuators. The `raw` endpoint (which is implemented by this API) is capable of doing all the things so you may need to change the API endpoints in your implementation a little bit. So basically this API is 100% backwards compatible in terms of features but you may need to change the endpoints.

| Sstadlberger's API | freeathome-api |
---------------------|----------------|
| `input` Endpoint | Removed, use `raw` Endpoint
| `set` Endpoint | Removed, use `raw` Endpoint
| `raw`Endpoint | 100% backwards-compatible
| `info` Endpoint | 100% backwards-compatible (master version from GitHub)
| Websocket updates | 100% backwards-compatible

**Comment by martin072** [comment]
Hi. Thanks for the quick reply. Yes I am using the set option in an url to set lights. Further more I am also using the websocket to query  status of the heating system and light states.

**Comment by henry-spanka** [comment]
Ok, got it. Changing the `set` endpoint to the equivalent `raw` endpoint should be done in a few minutes. Queries via Websocket are also supported.

**Comment by martin072** [comment]
Thanks. Will plan an upgrade for next weekend as I am not at home for a little while, and don't want to mess up the system now ;)
