### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by fabschub** [henry-spanka/freeathome-api#19]
Hi,

I am using nodejs 11 on debian buster.

> apt-cache policy nodejs
nodejs:
  Installiert:           11.15.0-1nodesource1
  Installationskandidat: 11.15.0-1nodesource1
  Versionstabelle:
 *** 11.15.0-1nodesource1 500
        500 https://deb.nodesource.com/node_11.x buster/main amd64 Packages
        100 /var/lib/dpkg/status
     10.15.2~dfsg-2 500
        500 http://ftp2.de.debian.org/debian buster/main amd64 Packages

I tried to install package via npm with no luck.
> npm install freeathome-api --save
npm WARN saveError ENOENT: no such file or directory, open '/opt/freeathome-api/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/freeathome-api/package.json'
npm WARN freeathome-api No description
npm WARN freeathome-api No repository field.
npm WARN freeathome-api No README data
npm WARN freeathome-api No license field.
freeathome-api@1.1.0
updated 1 package and audited 1322 packages in 2.339s
found 0 vulnerabilities

> ls -lah /opt/freeathome-api 
insgesamt 48K
drwxr-xr-x  3 freeathome freeathome 4,0K Dez 31 15:06 .
drwxr-xr-x 11 root       root       4,0K Dez 31 13:17 ..
drwxr-xr-x 81 freeathome freeathome 4,0K Dez 31 15:38 node_modules
-rw-r--r--  1 freeathome freeathome  34K Dez 31 14:59 package-lock.json

Is it just me or something went wrong with packaging? What to do?

Greetings and happy new year

Fabian

**Comment by henry-spanka** [comment]
Hello Fabian,
the path in the readme is incorrect. I have updated it now.

Please try to start the API with: `node node_modules/freeathome-api/bin/freeathome-api`

**Comment by fabschub** [comment]
Hi Henry,

thanks. It's working.
