### ISSUE TITLE
Docker image fails to start

### ISSUE THREAD

**Issue by henry-spanka** [henry-spanka/freeathome-api#2]
Container crashes with `Error: Cannot find module '/usr/src/app/dist/index.js`

**Comment by henry-spanka** [comment]
Fixed in f82e9adc23191694a4518593e2dd506c5f12c206

Please try to use the latest docker image (tag: latest) and let me know if it works. Image size is also reduced from 353 MB to 32 MB :)

**Comment by timboozle** [comment]
Yes I can confirm the Docker container works. Thanks for the great work!

I can't get it to work with my setup though. Like the poster in the other issue I would like to use this API with Homebridge.

I am running a Docker container for Homebridge (https://github.com/oznu/docker-homebridge) but it can't seem to connect to the other freeathome-api container:

```
[BuschJaegerSysAp] Error while communicating with SysAp
[BuschJaegerSysAp] Disconnected from SysAP
```

I tried with and without `--net=host`, localhost, and the Synology host, but no luck.

Sorry for going off topic but do you have any idea?

**Comment by henry-spanka** [comment]
Good to hear,
have you set the Websocket port mapping to 8001? As `homebridge-buschjaeger` uses a different port you need to change the port that `freeathome-api` uses.


Set the following while configuring the Port Settings in the Synology Docker Wizard

| Local Port | Container Port | Type
| -----------|---------------|-----|
| 8001 | 8081 | TCP

(If you use the command line use try `-p 8001:8081`)

**Comment by SchuldtOH** [comment]
Now it's working perfectly. Great work. Thanks!

**Comment by henry-spanka** [comment]
Great :) I'll try to release a new version this weekend which contains the fixes.
