### ISSUE TITLE
/info seems static

### ISSUE THREAD

**Issue by guckykv** [henry-spanka/freeathome-api#23]
Hi!

I've written a simple script which makes a GET to the web interface of freeathome-api path "/info" and filters out all RTR (Raumtemperaturregler). So I can draw a graph for the actual / target temperature.

But nothing changes. The values are all static. If i kill and restart the freeathome-api I get new values. But only once. Till the next api restart.

What's wrong? Does the api cache the values?

Regards,
Georg.

**Comment by henry-spanka** [comment]
Hi,
yes the API caches values, but listens for updates from the system access point. Therefore the cache values should always be correct.

I think the issue is already documented [here](https://github.com/henry-spanka/freeathome-api#known-issues). Have you tried that already?

**Comment by guckykv** [comment]
Thanks. Looks better now. I have a special api user so I normally don't use it for manual login.

But I don't think that the system access point was rebooted since I've started to use your api.

**Comment by henry-spanka** [comment]
👍 From what I have seen you need to login once after every reboot with the API user for it to work correctly. When you create a user for the API you also need to login once. I haven't found a fix for it yet.

**Comment by ZzAve** [comment]
I'd like to compare all messages that are send from the web implementation to the ones that are send through the API and checking the differences. 
From the webinterface I see two distinct calls for 'stream' and 'subscription', and although I have no clue what these'll actually do at the time of writing, it seems interesting to figure out what's going on there. Maybe I can do some digging tomorrow.

**Comment by henry-spanka** [comment]
There shouldn't be any difference between them. Let me know if you find something.

**Comment by draxels** [comment]
I have got the same problem /info reflects the value after API start-up (v 2.3.1, Windows 8) then no updates any more (of course the f@h app is correctly updated). Using a separate account as operator and did login/logout.
I would just need to check the status of the garage door - is there a way to poll this info ?

**Comment by henry-spanka** [comment]
Are all datapoint's static or only your garage door?

**Comment by draxels** [comment]
I have checked the weather data now - same story. Data is only updated at a restart of the API.

**Comment by henry-spanka** [comment]
Can you please try again to login with a separate user in the Web UI and control a few actuators and log out again. Then restart the API and it should hopefully work.

**Comment by draxels** [comment]
Yes, this seems to be the issue. After login/logout using the Web UI (same user) and not the App(s), data updates are received. I have never used the Web UI and forgot that it existed. Now I get the #18 error but this is a different subject and I can handle it. 
Thank you very much, I am enthusiastic user of your API !
