### ISSUE TITLE
V1.1.0 does not run on RasberryPi (Debian stretch)

### ISSUE THREAD

**Issue by Thomas-Schubert** [henry-spanka/freeathome-api#24]
I'm getting the Docker error "standard_init_linux.go:211: exec user process caused "exec format error"".

**Comment by ZzAve** [comment]
The current Docker image is build for linux (https://hub.docker.com/r/henryspanka/freeathome-api/tags) linux/amd64 architecture to be exact.  @henry-spanka Not 100% how you get your builds on docker hub, but it seems you do an automated build. If needed I can do a build for RaspberryPI 3 (armv7l) and publish that on henry's account if needed.

As a temporary workaround, you could build the Docker image yourself. Checkout the repo and run a `docker build -t henry-spanka/freeathome-api:armv7h`, after which you can run the container using that signature.

**Comment by henry-spanka** [comment]
Yep. We currently only build images for amd64 architecture. Builds are indeed automated and docker hub is currently limited to amd64 automated builds by default. Unfortunately building the image for a different platform didn't work. I will take a look at it next week. Until then you can try @ZzAve suggestion.

**Comment by Thomas-Schubert** [comment]
You guys are fantastic. I'll wait (it is not urgent) and then try plan B if the build still fails.

**Comment by henry-spanka** [comment]
I have now added images for armhf and armv8. Please try to use image tag `v1.1.0`

**Comment by Thomas-Schubert** [comment]
Thanks so much but I still get the following error (not sure whether this is a bug or a configuration issue on my side):

1/19/2020, 12:56:53 PM - INFO: Starting free@home API
/usr/src/app/dist/appRunner.js:33
        throw up;
        ^
Error: Could not connect to free@home API: this.settings.users is not iterable 
    at Application.<anonymous> (/usr/src/app/dist/lib/Application.js:34:23)
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/dist/lib/Application.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by henry-spanka** [comment]
Can you open `http://SYS_API_IP/settings.json` in your browser?

**Comment by henry-spanka** [comment]
I added some code that will check if the settings.json file downloaded from the SysAP is valid. In future releases you should get a meaningful error message.

**Comment by Thomas-Schubert** [comment]
You're great. If course I had the IP wrong (sorry to bug you with my mistake). It's all running now and I'm measuring whether info (light from the sensor) for my little home project to reduce my energy cost (by using the excess energy that our solar panels provide).

**Comment by henry-spanka** [comment]
👍 No problem, you're welcome.
