### ISSUE TITLE
 ERR: Your System Access Point's firmware must be at least 2.3.1

### ISSUE THREAD

**Issue by martin072** [henry-spanka/freeathome-api#25]
HI,

Maybe I am doing something wrong, but i've just update the Free@Home system to version 2.4.0 but when trying your API, I get the following:

1/23/2020, 11:50:43 AM - INFO: Starting free@home API
1/23/2020, 11:50:43 AM - ERR: Your System Access Point's firmware must be at least 2.3.1

When I Check the Setting Page in the Free@home Website it shows:

Version: 2.4.0 
Revision: 7568
Date: November 7th 2019 22:38:25

Any solutions for this? would really like to get my system back online with the API :)

**Comment by martin072** [comment]
I Believe I found the issue here...

in SystemAccesPoint.js it says:

 ```
connect() {
        return __awaiter(this, void 0, void 0, function* () {
            yield this.createClient();
            yield this.crypto.ready();
            this.crypto.generateKeypair();
            if (compare_versions_1.default(this.settings.flags.version, '2.3.1') >0) {
                Application_1.Application.error('Your System Access Point\'s firmware must be at least 2.3.1');
                Application_1.Application.exit(1);
            }
            try {
                yield this.client.start();
                this.sendKeepAliveMessages();
            }
            catch (e) {
                Application_1.Application.error('Could not connect to System Access Point', e.toString());
                Application_1.Application.exit(1);
            }
        });
    }
    disconnect() {
```

Should that not be:

 if (compare_versions_1.default(this.settings.flags.version, '2.3.1') <0)
??

**Comment by henry-spanka** [comment]
Hi Martin,
the issue was already reported in #13 and fixed in version 1.1.0. Make sure that the node package is up-to-date.

**Comment by martin072** [comment]
Hm's that is strange, I did an install this morning.. However, there was an older version installed.. does a new install not update?? I did run npm update just now and not sure is this worked. How can i check if the latest version is really installed?

**Comment by henry-spanka** [comment]
Do you have a `package.json` on your project directory? Try `npm update freeathome-api` or (if that doesn't work) `npm install freeathome-api@1.1.0`

**Comment by martin072** [comment]
I have a package.json listed, and it contains: "_id": "freeathome-api@1.0.1"

Trying to run the install gives me this:

`npm ERR! Could not install from "henry-spanka/freeathome-api@1.1.0" as it does not contain a package.json file.`

**Comment by martin072** [comment]
Thanks, so far so good now :)
