### ISSUE TITLE
Error: Not a valid Master Packet

### ISSUE THREAD

**Issue by hs75** [henry-spanka/freeathome-api#29]
dear all,

had a very stable installation that stopped working, debug message attached. login/out to api does not change error message. any help would be greatly appreciated.

best,

   holger 

4/12/2020, 04:09:11 - INFO: Starting free@home API
4/12/2020, 04:09:13 - INFO: Connected XXXXXXXXXXXXX@busch-jaeger.de/freeathome-api
4/12/2020, 04:09:13 - INFO: Websocket Server started
4/12/2020, 04:09:13 - INFO: Webserver Started
4/12/2020, 04:09:13 - INFO: Sent Authenticator
4/12/2020, 04:09:13 - INFO: Received Local Key
4/12/2020, 04:09:13 - INFO: Sent New Session Request
4/12/2020, 04:09:13 - INFO: Sent Login SASL Message
4/12/2020, 04:09:13 - INFO: Received SASL Challenge
4/12/2020, 04:09:13 - INFO: Sent SASL Challenge Response
4/12/2020, 04:09:13 - INFO: Received SASL Login Confirmation
4/12/2020, 04:09:13 - INFO: Successfully Authenticated
4/12/2020, 04:09:13 - INFO: Announced Capabilities to System Access Point
4/12/2020, 04:09:13 - INFO: Requested Master Data Structure from System Access Point
4/12/2020, 04:09:15 - INFO: Received Master Update from System Acccess Point
/usr/local/lib/node_modules/freeathome-api/dist/appRunner.js:33
        throw up;
        ^

Error: Not a valid Master Packet
    at Function.parseDeviceData (/usr/local/lib/node_modules/freeathome-api/dist/lib/XmlParser.js:27:23)
    at Function.parseMasterUpdate (/usr/local/lib/node_modules/freeathome-api/dist/lib/XmlParser.js:17:21)
    at SystemAccessPoint.<anonymous> (/usr/local/lib/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:257:53)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:4:12)
    at SystemAccessPoint.handleRpcCallResult (/usr/local/lib/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:236:16)
    at SystemAccessPoint.<anonymous> (/usr/local/lib/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:210:26)
    at Generator.next (<anonymous>)

**Comment by henry-spanka** [comment]
Hi,
the error is thrown if the master update does not contain the string dictionary or floorplan.

Which firmware version is installed on the System Access Point?

**Comment by hs75** [comment]
Version 2.4.0
Revision 7586
Date 7 Nov 19 19:02:18

**Comment by henry-spanka** [comment]
Hi,
please edit the file /usr/local/lib/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js manually and find the following line

`this.logger.log("Received Master Update from System Acccess Point");`
and add a new line directly below it
`this.logger.log(message);`

It should look like this afterwards:

```javascript
...
catch (e) {
    throw new Error("Failed to parse rpc call result JSON: " + e.toString());
}
this.logger.log("Received Master Update from System Acccess Point");
this.logger.log(message);
this.deviceData = XmlParser_1.XmlParser.parseMasterUpdate(message.value);
if (!this.subscribed) {
    yield this.sendMessage(this.messageBuilder.buildSubscribeMessage());
    this.logger.log("Sent Subscription Request");
}
...
```

Restart the API and send me log again. It should contain some XML data.

**Comment by hs75** [comment]
just forwarded it by mail.

best,

     holger

**Comment by henry-spanka** [comment]
Log looks OK. No issues. Please send log again when the API crashes.

**Comment by hs75** [comment]
Hallo Henry,

ich wollte mich nochmal bei Dir für den Support bedanken. Nach einigem hin und her funktioniert meine Installation wieder. Ich vermute, dass das der Fehler durch unzulässige Namen zwischen Hue, Free@home und Homebridge entstanden ist. 
Noch eine Kleinigkeit ist mir aufgefallen: Im Beschreibungstext sagst Du irgendwann, dass das API auf port 8001 läuft, in der Config steht Port 8081. Vielleicht magst Du beides mal angleichen.

Viele Grüße,

   Holger

**Comment by henry-spanka** [comment]
👍 Die API und das Homebridge Plugin sind zwei separate Projekte. In Homebridge den Port anzupassen macht nicht wirklich sinn, weil dann alle bereits konfigurierten Homebridge's nicht mehr funktionieren. In der Installationsanleitung vom Plugin steht aber auch drinne, dass der Port geändert werden muss.

Siehe auch https://github.com/henry-spanka/homebridge-buschjaeger/issues/15
