### ISSUE TITLE
Enhance backward compatibility

### ISSUE THREAD

**Issue by SchuldtOH** [henry-spanka/freeathome-api#3]
Hi,

it would be great if you could add the possibility to use
/info/{serialNo}/{channel}/{datapoint}
This was possible in the Stadlberger API and is useful if someone does not want to handle the full json output.

Thanks!

**Comment by henry-spanka** [comment]
True thing. I will implement it this weekend. Unfortunately my Single-Board-Computer (ODROID N2) died today and I first need to get this fixed as HomeKit doesn't work anymore and my Garage doesn't work either 😢 Will try to get a Raspberry Pi 4 tomorrow from a friend 😉

**Comment by SchuldtOH** [comment]
Another differece to the Stadlberger API is, that previously ip-adress/set/switch/ABBxxxxx/ch0010/on was working. 

From the readme documentation I see that now the command should be
ip-adress/raw/ABBxxxx/ch0010/odp0000/1
Unfortunately this does not work for me. I get a result "ABBxxxxx/ch0010/odp0000: 1" in the browser and "INFO: Set Datapoint: ABBxxxxx/ch0010/odp0000/1" in the log. But the switch is not turned on.

**Comment by henry-spanka** [comment]
Hi,
yes I removed any unnecessary API endpoints as I think the `/set` endpoint is not well maintained. 
Please try: `ABBxxxxx/ch0010/idp0000/1`

`odpXXXX` are output datapoints. Meaning they cannot be set (at least it won't change anything). Always use `idXXXX` (input datapoints) when trying to control an accessory. Additionally there are `pmXXXX` datapoints. They are parameters that can also be set (e.g. time for a shutter to completely close).

I may add the endpoint again in the future but I don't think it makes sense now. I will maybe add a table to the readme which explains which datapoints to use for which actuator.

**Comment by SchuldtOH** [comment]
I agree, these endpoints are indeed unnecessary.
It works fine with idxxxx.

**Comment by ZzAve** [comment]
@SchuldtOH With regards to your original request, about device / channel traversal on the /info endpoint, this has been available since 15 October: https://github.com/henry-spanka/freeathome-api/commit/41385f37216ec66a3657dc36b5f7a0b5e3436d06

Let me know if this is enough to close the issue :)

**Comment by SchuldtOH** [comment]
Yes. This works perfectly now and can be closed.
