### ISSUE TITLE
Question: Is Version 2.5.0 Supported

### ISSUE THREAD

**Issue by martin072** [henry-spanka/freeathome-api#30]
Hi, just got a message Version 2.5.0 is available for B+J Free@Home. Any one already running this together with Henry's Api?

**Comment by henry-spanka** [comment]
👍Works fine for me. See: https://github.com/henry-spanka/freeathome-api#tested-versions

**Comment by martin072** [comment]
Will put my glasses 🤓 on next time 😉
Thanks
