### ISSUE TITLE
Unexpected error while processing stanza event

### ISSUE THREAD

**Issue by emptygalaxy** [henry-spanka/freeathome-api#31]
I keep getting the 'Unexpected error while processing stanza event' error when processing incoming events. I've added extra validation in SystemAccessPoint.parseEncryptedUpdates that I will make a PR for.

  TypeError: Cannot read property 'attrs' of undefined
      at node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:140:124

**Comment by henry-spanka** [comment]
Hi,

I believe this was already fixed in #18. However I haven't released a new version yet so the fix is only available in the master version.
