### ISSUE TITLE
INFO: Sent Subscription Confirmation stucks

### ISSUE THREAD

**Issue by Alox-K** [henry-spanka/freeathome-api#32]
Hi,
after starting the api the message "INFO: Sent Subscription Confirmation" stucks on terminal. Nothin happens and the plugin doesn't work.
Any idea?

**Comment by henry-spanka** [comment]
Hi,
which firmware version do you have installed on your SysAp?

**Comment by henry-spanka** [comment]
Well,
actually it isn't stuck. You need to run the API in the background 24/7. It will not print anything after that.

**Comment by Alox-K** [comment]
Thanks for your quick answer!
I have 2.5.0
But finally... I realized this has been a case of "RTFM".
I didn't set the port of the websocket to 8001. After changing it, "websocket connection established" appeared and I got it done!
Thank you!
