### ISSUE TITLE
Error when node node_modules/freeathome-api/bin/freeathome-api

### ISSUE THREAD

**Issue by Babelbernd** [henry-spanka/freeathome-api#33]
I get this error when typing following: 

root@pi:~/home# node node_modules/freeathome-api/bin/freeathome-api
4.9.2020, 01:30:12 - INFO: Could not read/parse configuration file - Trying to use environment instead
4.9.2020, 01:30:12 - ERR: Required environment variables (hostname, username, password not set

Did i setup the config.json properly?

{
    "hostname": "System-Access-Point",
    "username": "Installer", 
    "password": "XXXXXXXX",
    "httpApi": {
        "enabled": true,
        "address": "127.0.0.1",
        "port": 8080
    },
    "wsApi": {
        "enabled": true,
        "address": "127.0.0.1",
        "port": 8081
    },
    "debug": false
}

**Comment by henry-spanka** [comment]
Hi,
the config looks correct. Make sure that you have placed the config file in your working directory.

**Comment by Babelbernd** [comment]
Thank you, the file was in the wrong directory .
