### ISSUE TITLE
Any issues with 2.5.4?

### ISSUE THREAD

**Issue by martin072** [henry-spanka/freeathome-api#35]
Hi all, currently running 2.5.2 and since a few days the w websocket seems to drop all the time after being stable for months. I do need to dive into it, but was wondering if it is safe to update to 2.5.4? 

Thanks

**Comment by henry-spanka** [comment]
Hi, I have 2.5.2 installed as well and did not have any stability issues yet. Haven't tried 2.5.4 yet but it's usually safe to do minor software upgrades.

**Comment by henry-spanka** [comment]
Closing due to no feedback.
