### ISSUE TITLE
Parse room name and device type (light, outlet, etc.) from master structure

### ISSUE THREAD

**Issue by henry-spanka** [henry-spanka/freeathome-api#4]
As requested in henry-spanka/homebridge-buschjaeger#13

Additionally to the device names we should expose the room name and possible the device type (light, outlet, etc.). Maybe it's even possible to expose the device's name as appearing on the free@home device layout.

**Comment by henry-spanka** [comment]
I added some commits to the master branch. The following attributes are now exposed for each channel (if available):
* **displayName**: Name of the channel as appearing on the free@home device layout
* **floor**: Name of the floor where the channel is placed on the free@home device layout
* **room**: Name of the room where the channel is placed on the free@home device layout
* **iconId**: ID of the icon this channel has. I couldn‘t figure out which id corresponds to which icon, but you should be able to check that yourself

**Comment by timboozle** [comment]
Wow this is great!
I have both lights and outlets which correspond to iconId "1" for lights and "a" for outlets.
