### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by OscarNOW** [henry-spanka/freeathome-api#43]
I'm currently using `freeathome-api@1.1.1` . I can currently get a list of all devices and set specific devices using `systemAccessPoint.setDatapoint` and `systemAccessPoint.getDeviceData`. I wan't to know how I could get the status of one (or all) devices. On the npm package page, it says to 

> send the following payload: info

, but I don't know how to send payloads, I just use the npm package. Any help would be appreciated.

**Comment by henry-spanka** [comment]
You can use `getDeviceData` to read the datapoints and status of the devices.
