### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by mobilutz** [henry-spanka/freeathome-api#52]
@henry-spanka This is a question not an issue.

In the Readme, it is stated that SysAp V3.0 is supported.

What is with the other versions:
1. v3.1
2. v3.2

I seem to have error in a usecase of the npm module: https://github.com/mobilutz/ioBroker.freeathome/issues/654

Thanks

**Comment by henry-spanka** [comment]
Should be supported. I am running latest firmware on SysAp and working so far.
