### ISSUE TITLE
Add support for IP-Gateway and intercom

### ISSUE THREAD

**Issue by henry-spanka** [henry-spanka/freeathome-api#9]
It would be nice if we could access the intercom via the free@home IP-Gateway.

Unfortunately only apps for Android and iOS devices exist and the relevant code is packaged as machine code (.so files) making it difficult to reverse engineer it.

Internally the apps use SIP (linphone library) to communicate with the intercom (video + 2-way audio). Communication is secured using client certificates and TLS. If we could get our hands on the SIP username and the client certificates we may be able to get this working.

**Comment by henry-spanka** [comment]
Well, I managed to extract the sip certificates and could successfully call the intercom with Linphone. Now we need some way to convert the SIP stream (both ways) to some handy format :(

We could try https://github.com/alfredh/baresip

**Comment by emptygalaxy** [comment]
Did you figure out how to make this work? I’m looking to purchase a IP gateway to see if I can get it to work. Did you use the 83320 or is it essentially an expensive wire splitter?

**Comment by henry-spanka** [comment]
I tried it with the intercom. However I abandoned the project as it's far too much work and I don't have a real usage case for it anyway as I have a standalone camera for this (not integrated in BJ).

**Comment by henry-spanka** [comment]
Closing this as I don't see this happen anytime soon. The IP-Gateway is basically a black box and requires much reverse engineering and is using the SIP protocol.
